# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6dec3181857fef134c4b35ad1cc48b2a6bd45b4960bba18c944f19001596605aebc3b8f53e5a63204e6eddd5415d12673c144d5468225a4e7b4fa916d7ee9b

test:
  secret_key_base: c3caa6d063a1c383d397fe76501a461835198e0f3682582b2da97c57eede7441a43620d0ce3c764e30e2098b18f555e2d357fd5b5afb4052ce87ad8a9c6bac78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
